version: "3.9"

services:
  pathway_rag:
    build:
      context: ./pathway_rag
      dockerfile: Dockerfile
    ports:
      - "4005:4005" # Keep 4005 for pathway_rag internally
    networks:
      - app-network
    command:
      [
        "bash",
        "-c",
        "fuser -k 4005/tcp && python3 rag_server.py & python3 pw_new.py & python3 http_serve.py & python3 pw_userkb.py & wait",
      ]

  raccoon:
    build:
      context: ./RACCOON
      dockerfile: Dockerfile
    ports:
      - "4006:4005" # Map raccoon to port 4006 externally
    networks:
      - app-network
    volumes:
      - ./RACCOON:/app # Optional: if you need to persist files
    command: ["bash", "-c", "python3 main.py & python3 change.py & wait"]

  tm13_ui:
    build:
      context: ./TM13-UI
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
